---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "subscription1"
  labels:
    kind.funktion.fabric8.io: "Subscription"
    connector: "timer"
data:
  application.properties: |
    # spring application proeprties file
    welcome = Hello from Kubernetes ConfigMap!!!
    dummy = some value
  funktion.yml: |
    ---
    rules:
      - trigger: timer://foo?fixedRate=true&period=5000
        trace: true
        actions:
        - kind: endpoint
          url: http://fabric8-forge/
        - kind: endpoint
          url: log:example
