---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "subscription1"
  labels:
    funktion.fabric8.io/kind: "Subscription"
    connector: "timer"
data:
  application.properties: |
    # spring application properties file
    foo = bar
  funktion.yml: |
    ---
    flows:
      - logResult: true
        steps:
        - kind: endpoint
          uri: timer://foo?fixedRate=true&period=5000
        - kind: endpoint
          uri: http://ip.jsontest.com/
